[run]
init_cmds = [
	["go", "install"],
	["vessel", "web"]
]
watch_all = true
watch_dirs = [
	"../modules",
	"../cmd",
	"../models",
	"$GOPATH/src/github.com/dockercn/rudder",
	"$GOPATH/src/github.com/dockercn/anchor"
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
	["go", "install"],
	["vessel", "web"]
]